### ISSUE TITLE
Python 3: _check_types() fails on binary uint8[]

### ISSUE THREAD

**Issue by mvollrath** [ros/genpy#122]
```python
import rospy
from std_msgs.msg import UInt8MultiArray
m = UInt8MultiArray(data=bytes([0, 1, 2]))
m._check_types()
```

The check passes on melodic, but fails on noetic:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 362, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 281, in check_type
    raise SerializationError('field %s must be a list or tuple type' % field_name)
genpy.message.SerializationError: field data must be a list or tuple type
```

Is assigning `bytes` no longer accepted?

**Comment by dirk-thomas** [comment]
Please see #123 for the proposed fix. Note that this isn't a regression and specific to the usage of Python 3.
